### ISSUE TITLE
Unnecessary runtime dependency to Library induced by boost::gregorian::greg_month

### ISSUE THREAD

**Issue by xgcssch** [boostorg/date_time#107]
### Environment
Boost Version: 1.70
Compiler: Visual Studio 2017 – 15.9.12
OS: Windows 10

### Steps to reproduce:

1. Install boost-date-time via vcpkg
2. Create Windows Console Project and integrate vcpkg packages
3. Use the following testfile
```cpp
#include "pch.h"
#include <boost/date_time/gregorian/greg_month.hpp>
int main()
{
    boost::gregorian::greg_month m(1);
    return 0;
}
```
4.	Compile.program
### Expected behavior:
The resulting file should have no references to the boost dll.

### Observed behaviour:
The resulting file has a reference:

```
dumpbin /nologo /imports:boost_date_time-vc141-mt-gd-x32-1_70.dll DateTimeLinkDependency.exe

Dump of file DateTimeLinkDependency.exe

File Type: EXECUTABLE IMAGE

  Section contains the following imports:

    boost_date_time-vc141-mt-gd-x32-1_70.dll
                41B0E0 Import Address Table
                41B328 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                    2 ??0greg_month@gregorian@boost@@QAE@G@Z
```
### Temporary fix:
Change in `boost\date_time\gregorian\greg_month.hpp`:

From 
```
class BOOST_DATE_TIME_DECL greg_month : public greg_month_rep {
```
to 
```
class BOOST_SYMBOL_VISIBLE greg_month : public greg_month_rep {
```
after that:
```
Dump of file DateTimeLinkDependency.exe

File Type: EXECUTABLE IMAGE

  Section contains the following imports:

  Summary

        1000 .00cfg
        1000 .data
        1000 .idata
        1000 .msvcjmc
        4000 .rdata
        1000 .reloc
        1000 .rsrc
        D000 .text
       10000 .textbss
```
### Impact
All our programs using date_time::gregorian::date must be accompanied by the date_time dll.

The behavior seems a little bit similar to #34!?

Best regards
Sönke

**Comment by jeking3** [comment]
This will be resolved by #85, eliminating the link library all-together.

**Comment by xgcssch** [comment]
Ok!
Thanks for maintaining this project!!
Best regards
Sönke

**Comment by jeking3** [comment]
I do what I can; but appreciate any assistance in addressing issues. :)

**Comment by JeffGarland** [comment]
I'm hoping to keep contributing again.  @jeking3 do we not have a branch with changes to finally solve #85 somewhere?  Or are we still waiting for an implementation?  I think post c++11 removing the library gets even easier to implement...

**Comment by jeking3** [comment]
Work hasn't started yet on #85.
