### ISSUE TITLE
Use constexpr in date_time

### ISSUE THREAD

**Issue by rogerorr** [boostorg/date_time#123]
Certain of the methods in date_time would benefit from being marked `constexpr`.

For example, being able to use `time_duration::ticks_per_second()` in a constexpr context would be useful. This returns `rep_type::res_adjust()` which in turn seems to come from the `resolution_adjust` NTTP from `time_resolution_traits` .

**Comment by JeffGarland** [comment]
Thanks Roger -- will look at this.  Just to fill in from the discussion we had in Prague, you've observed a significant performance benefit from having the adjustment parameters calculated at compile time which simplifies the run time calculations.

**Comment by rogerorr** [comment]
Correct. We had code which needed to divide by the ratio between 1e7 and `ticks_per_second`.
This generated a full divide operation - the compiler did not optimise through the two calls. Marking the ratio and the two calls mentioned above as `constexpr` allows the compiler to divide by a compile-time constant which is optimised to a multiply using the standard transformation in such cases.

**Comment by JeffGarland** [comment]
The initial set of library changes is now complete on branch dt_constexpr -- compiles and runs all unit tests successfully with gcc9.2 with c++ versions: 98, 11, 14, 17, 2a.  Now waiting for the CI to test against all the compilers.  Also should add a test that explicitly exercises the constexpr to see what has been achieved.

**Comment by rogerorr** [comment]
Hello @JeffGarland -- I haven't been in a position to check this until now; but I can confirm the `constexpr` change is working successfully for the use case I presented. 
Thank you!

**Comment by JeffGarland** [comment]
You're welcome.  The changes have been pushed to master so this will be in the 1.73 release.  I'm leaving this open until all the docs and such are finished

**Comment by rogerorr** [comment]
The changes in 1.73.0 have made measurable improvements to some of our performance benchmarks -- thanks for this!

I'm looking at making some more of our constants `constexpr` and there seems to be a missing `BOOST_CXX14_CONSTEXPR` on the `assign` method of `constrained_value` which prevents the constructors (which call assign) being constexpr. Happy to raise a fresh ticket if you'd like, or leave this here -- whichever is best for you :)

**Comment by JeffGarland** [comment]
Glad it was useful, and thanks -- indeed assign got missed.  I'll just keep working it under this ticket as I wanted to expand the tests a bit anyway to make sure it was covered.

**Comment by rogerorr** [comment]
Sounds fine. Good luck!

**Comment by JeffGarland** [comment]
Assign and new tests are all complete and will be part of the 1.74 release.  This is now complete.
