### ISSUE TITLE
typos in documentation

### ISSUE THREAD

**Issue by Xeverous** [boostorg/date_time#127]
https://www.boost.org/doc/libs/1_72_0/doc/html/date_time/posix_time.html#date_time.posix_time.ptime_class

- `tm_isdst` vs `tm_isddst` (just ctrl+F them)
- `ptime microsec_clock::local_time()` and `ptime microsec_clock::universal_time()` have: *On Unix systems this is implemented using GetTimeOfDay. On most Win32 platforms it is implemented using ftime.*

**Comment by JeffGarland** [comment]
Thanks.  tm_isddst will be fixed on branch for issue #123. Not sure I'm following the suggestion on the second bullet?

**Comment by Xeverous** [comment]
The documentation mentioned on the second bullet has wrong (reversed) function names.

**Comment by JeffGarland** [comment]
So you're saying ftime on *nix?  Look at date_time/microsecond_clock.hpp -- ftime is winapi and GetTimeOfDay is *nix. Technically for Windows it's:
 
      boost::winapi::FILETIME_ ft;
      boost::winapi::GetSystemTimeAsFileTime(&ft);

So I think the documentation is accurate.

**Comment by Xeverous** [comment]
Ok, I haven't checked the code before the issue but seeing:

- "on most Win32 platforms / on Unix systems" sounds weird/reversed as Unix has much more OS variants than Windows
- Functions on Unix systems usually come from POSIX, so a name like `ftime` seemed analogical to eg `fopen`, `fwrite`. WinAPI has PascalCase names so that was another suspicion that names are reversed in documentation.

**Comment by JeffGarland** [comment]
yes, the camel case is misleading:

http://man7.org/linux/man-pages/man2/gettimeofday.2.html

**Comment by Xeverous** [comment]
Ahh, now it looks like a unix function. I think you should correct it too, C++ is case-sensitive.

**Comment by JeffGarland** [comment]
Fixed in commit 415dd10.  Will be part of boost 1.73.
