### ISSUE TITLE
header-only date_time breaks Wave build

### ISSUE THREAD

**Issue by jefftrull** [boostorg/date_time#136]
Wave, and perhaps other Boost libraries, attempt to link against date_time. New CI builds for those libraries are failing. Could there be a provision for a helpful error message, or perhaps a "stub" library similar to the one provided for System?

**Comment by JeffGarland** [comment]
yep, ok @pdimov must made the same point -- I can do something there.  Honestly I thought I'd searched boost for date_time references -- apparently I missed with my regex.

**Comment by JeffGarland** [comment]
pull request #137 -- waiting for CI to merge to develop

**Comment by JeffGarland** [comment]
resolved

**Comment by jefftrull** [comment]
Thanks Jeff! I took them out of Wave but that will help others.
