### ISSUE TITLE
Const-qualify read and comparison methods of boost::date_time::time_itr + boost::date_time::date_itr_base

### ISSUE THREAD

**Issue by trueqbit** [boostorg/date_time#168]
I was wondering why the read and comparison methods of `boost::date_time::time_itr` + `boost::date_time::date_itr_base` (files boost/date_time/time_iterator.hpp and boost/date_time/date_iterator.hpp) aren't const-qualified.

Specifically:

    template<class time_type>
    class time_itr {
    public:
      time_type operator*() {return current_;}
      time_type* operator->() {return &current_;}
      bool operator<  (const time_type& t) {return current_ < t;}
      bool operator<= (const time_type& t) {return current_ <= t;}
      bool operator!=  (const time_type& t) {return current_ != t;}
      bool operator== (const time_type& t) {return current_ == t;}
      bool operator>  (const time_type& t) {return current_ > t;}
      bool operator>= (const time_type& t) {return current_ >= t;}
    private:
      time_type current_;
    };

    template<class date_type>
    class date_itr_base {
    public:
      date_type operator*() {return current_;}
      date_type* operator->() {return &current_;}
      bool operator<  (const date_type& d) {return current_ < d;}
      bool operator<= (const date_type& d) {return current_ <= d;}
      bool operator>  (const date_type& d) {return current_ > d;}
      bool operator>= (const date_type& d) {return current_ >= d;}
      bool operator== (const date_type& d) {return current_ == d;}
      bool operator!= (const date_type& d) {return current_ != d;}
    private:
      date_type current_;
    };

Is there any reason not to const-qualify them? They don't modify their state,  and I presume they shouldn't.
It would be useful as I could then make my/our code more const-correct.

**Comment by JeffGarland** [comment]
yes, that looks like a bug to me. I suspect this is a little used feature of the library which would explain why this went unnoticed for 15+ years.

**Comment by trueqbit** [comment]
Well, I discovered a nice application in regard to iteration over time and date. Now that I see the library in active develop and fix mode, I thought I was addressing this issue.
