### ISSUE TITLE
Compilation issues in time_system_split for Apple clang version 12.0

### ISSUE THREAD

**Issue by wsobel** [boostorg/date_time#185]
Seems like a clang bug causing the misinterpretation of a less-than operator. 

The following statement:

    static BOOST_CXX14_CONSTEXPR
    bool is_less(const time_rep_type& lhs, const time_rep_type& rhs)
    {
      if (lhs.day < rhs.day) return true;
      if (lhs.day > rhs.day) return false;
      return (lhs.time_of_day < rhs.time_of_day); // < being misinterpreted
    }

is generating an error: "Exected '>'"

Workaround:

    static BOOST_CXX14_CONSTEXPR
    bool is_less(const time_rep_type& lhs, const time_rep_type& rhs)
    {
      if (lhs.day < rhs.day) return true;
      if (lhs.day > rhs.day) return false;
      return ((lhs.time_of_day) < rhs.time_of_day); // < being misinterpreted
    }

**Comment by JeffGarland** [comment]
Unfortunately we don't have apple platform as part of the boost test suite and I'm at a loss to understand how this can be misinterpreted and how the change fixes the issue. Is there an issue filed against apple clang somewhere? Not sure I want to make a change for a compiler this broken....

**Comment by mclow** [comment]
I can try it - if I can get a complete test case.

**Comment by wsobel** [comment]
Founds a fix by putting the includes for 

```
#include <boost/asio/ip/tcp.hpp>
#include <boost/asio/steady_timer.hpp>
```

Before any other includes.

There is some contention with another system library. I have not had time to check which file is conflicting. 

Thx - W
