### ISSUE TITLE
Looks like develop and master diverged...

### ISSUE THREAD

**Issue by jeking3** [boostorg/date_time#203]
https://github.com/boostorg/date_time/compare/develop...master

I can remedy, @JeffGarland, just wondering what happened there and if it was intentional.

1. Merge master into develop.
2. Merge develop into master.

**Comment by JeffGarland** [comment]
it was not intentional -- and yeah not sure what happened there, but the plan is correct.  I assume step 2 will be a noop

**Comment by jeking3** [comment]
Fixed.
