### ISSUE TITLE
Y2K38 Bug:  from_time_t is unnecessarily forcing 32-bit seconds

### ISSUE THREAD

**Issue by jrnphd** [boostorg/date_time#209]
The bug reported in https://github.com/boostorg/date_time/issues/87 is still present in boost version 1.79.0

The fix is trivial:

`--- boost/date_time/posix_time/conversion.hpp
+++ boost/date_time/posix_time/conversion.hpp
@@ -26,7 +26,7 @@
  inline
  ptime from_time_t(std::time_t t)
  {
-    return ptime(gregorian::date(1970,1,1)) + seconds(static_cast<long>(t));
+    return ptime(gregorian::date(1970,1,1)) + seconds(t);
 } 
`

**Comment by jeking3** [comment]
This is fixed by #80 which did not make it into Boost 1.79 - it will be in Boost 1.80
