### ISSUE TITLE
Anomaly when running tests

### ISSUE THREAD

**Issue by eldiener** [boostorg/date_time#51]
I am seeing a strange anomaly when running date_time tests, both locally and in the regression tests. The xml serialization tests show all tests passing and yet the tests return a non-0 code indicating run-time failure. In looking at the code in testfrmwk.hpp, which prints the total results of the tests and then returns a difference between the tests run and the tests passed, the total results printout is predicated on whether tests passed != tests run or not, which shows they are equal, but the subsequent return, which is tests run - tests passed shows 3 more tests run than passed ! This suggests that something is getting overwritten in memory between one line and the next, but I have no idea why this is happening. If anybody else can trace this down it would be very helpful, since the regression tests show these tests failing across the board, where they are actually succeeding according to the test results.

**Comment by jeking3** [comment]
Do you still see this with Boost 1.66.0?  There were a number of changes in Boost.Serialization, for example the singleton correctness, which might have played a part in what you describe (just a guess).

**Comment by eldiener** [comment]
This was fixed by a change Peter Dimov made.

**Comment by jeking3** [comment]
Nice, sounds like the issue can be closed.

**Comment by jeking3** [comment]
(might want to close this)
