### ISSUE TITLE
from_time_t is unnecessarily forcing 32-bit seconds

### ISSUE THREAD

**Issue by jeking3** [boostorg/date_time#87]
See: https://github.com/boostorg/date_time/pull/35#issuecomment-353632702
https://github.com/boostorg/date_time/commit/b1dc2b306ea6abb645b0e334e3d5bb1b5ed80818

**Comment by jrnphd** [comment]
Boost 1.77.0 still has this bug.  The fix appears to be simple enough:

--- boost/date_time/posix_time/conversion.hpp
+++ boost/date_time/posix_time/conversion.hpp
@@ -26,7 +26,7 @@
  inline
  ptime from_time_t(std::time_t t)
  {
-    return ptime(gregorian::date(1970,1,1)) + seconds(static_cast<long>(t));
+    return ptime(gregorian::date(1970,1,1)) + seconds(t);
  }
